import type {
  Accommodation,
  Activity,
  AppSettings,
  Flight,
  PackingItem,
  Reminder,
  Transport,
  Trip,
} from './types';

const now = '2026-07-31T00:00:00.000Z';
export const londonTripId = 'trip-london-2026';

export const initialTrips: Trip[] = [
  {
    id: londonTripId,
    name: 'Londres en familia 2026',
    destination: 'Londres',
    country: 'Reino Unido',
    startDate: '2026-08-01',
    endDate: '2026-08-05',
    coverImage: '/london-hero.png',
    description: 'Primer viaje familiar organizado con TravelCaris.',
    currency: 'GBP',
    secondaryCurrency: 'EUR',
    exchangeRate: 1.18,
    travellers: [],
    status: 'Próximo',
    createdAt: now,
    updatedAt: now,
  },
];

const activity = (
  order: number,
  day: Activity['day'],
  startTime: string,
  title: string,
  category: Activity['category'],
  description: string,
  address: string,
  lat?: number,
  lng?: number,
  extras: Partial<Activity> = {},
): Activity => ({
  id: `${day}-${order}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
  tripId: londonTripId,
  title,
  description,
  date: day,
  startTime,
  endTime: extras.endTime ?? '',
  estimatedDurationMinutes: extras.estimatedDurationMinutes ?? 90,
  category,
  address,
  lat,
  lng,
  mainImage: extras.mainImage,
  gallery: [],
  adultPrice: extras.adultPrice ?? 0,
  childPrice: extras.childPrice ?? 0,
  estimatedTotalPrice: extras.estimatedTotalPrice ?? 0,
  currency: extras.currency ?? 'GBP',
  reservationRequired: extras.reservationRequired ?? false,
  reservationDone: extras.reservationDone ?? false,
  reservationReference: '',
  reservationLink: extras.reservationLink ?? '',
  officialLink: extras.officialLink ?? '',
  phone: '',
  notes: extras.notes ?? '',
  status: extras.status ?? 'Pendiente',
  priority: extras.priority ?? 'Media',
  tags: extras.tags ?? [],
  day,
  order,
  visited: false,
  favorite: extras.favorite ?? false,
  createdAt: now,
  updatedAt: now,
});

export const initialActivities: Activity[] = [
  activity(1, '2026-08-01', '06:05', 'Vuelo Alicante-Londres Gatwick', 'Transporte', 'Vuelo Vueling VY8475. Llegada a Gatwick terminal sur a las 07:50.', 'Alicante Airport to London Gatwick Airport', 51.1537, -0.1821, { status: 'Confirmado', tags: ['VY8475', 'aeropuerto'] }),
  activity(2, '2026-08-01', '08:45', 'Traslado Gatwick-Londres', 'Transporte', 'Thameslink hasta St Pancras y taxi corto hasta el alojamiento.', 'Gatwick Airport to 23 Theobalds Road, London', 51.5194, -0.1166),
  activity(3, '2026-08-01', '10:30', 'Primer alojamiento', 'Alojamiento', 'Flat 3, 23 Theobalds Road, Camden, Londres WC1X 8SL.', '23 Theobalds Road, London WC1X 8SL', 51.5194, -0.1166, { status: 'Confirmado' }),
  activity(4, '2026-08-01', '12:00', 'British Museum', 'Museo', 'Visita familiar. Entrada general gratuita, recomendable reservar franja gratuita.', 'British Museum, Great Russell Street, London', 51.5194, -0.127),
  activity(5, '2026-08-01', '14:00', 'Seven Dials', 'Restaurante', 'Paseo y posible comida. Sugerencias: Pizza Pilgrims o Seven Dials Market.', 'Seven Dials, London', 51.5147, -0.126),
  activity(6, '2026-08-01', '16:00', 'Covent Garden', 'Paseo', 'Mercado, artistas callejeros y paseo por la zona.', 'Covent Garden, London', 51.5117, -0.123),
  activity(7, '2026-08-01', '18:00', 'Leicester Square', 'Actividad infantil', 'LEGO Store, M&M’s London y ambiente familiar.', 'Leicester Square, London', 51.5107, -0.1301),
  activity(8, '2026-08-01', '20:00', 'Chinatown', 'Restaurante', 'Paseo y cena en Chinatown.', 'Chinatown, London', 51.511, -0.1318),
  activity(1, '2026-08-02', '09:30', 'Palacio de Westminster y Big Ben', 'Monumento', 'Visita exterior.', 'Palace of Westminster, London', 51.4995, -0.1248),
  activity(2, '2026-08-02', '10:30', 'Westminster Abbey', 'Monumento', 'Visita exterior inicialmente. Entrada interior como actividad opcional.', 'Westminster Abbey, London', 51.4993, -0.1273),
  activity(3, '2026-08-02', '11:30', 'Free tour por Westminster', 'Reserva', 'Actividad reservable. Completar empresa, punto de encuentro y enlace cuando se confirme.', 'Westminster, London', 51.5007, -0.1246, { reservationRequired: true, status: 'Alternativa' }),
  activity(4, '2026-08-02', '13:00', 'St James’s Park', 'Parque', 'Paseo familiar.', 'St James’s Park, London', 51.5025, -0.1348),
  activity(5, '2026-08-02', '14:30', 'Buckingham Palace', 'Monumento', 'Visita exterior. Comprobar calendario oficial del cambio de guardia.', 'Buckingham Palace, London', 51.5014, -0.1419, { notes: 'Revisar calendario oficial del cambio de guardia.' }),
  activity(6, '2026-08-02', '16:30', 'National Gallery', 'Museo', 'Entrada general gratuita.', 'National Gallery, Trafalgar Square, London', 51.5089, -0.1283),
  activity(7, '2026-08-02', '19:00', 'South Bank', 'Paseo', 'Paseo junto al Támesis. London Eye opcional y cena por la zona.', 'South Bank, London', 51.5033, -0.1195),
  activity(1, '2026-08-03', '09:30', 'Natural History Museum', 'Museo', 'Entrada gratuita, reserva recomendada. Prioridad para los niños.', 'Natural History Museum, London', 51.4967, -0.1764, { priority: 'Alta', reservationRequired: true }),
  activity(2, '2026-08-03', '12:30', 'Science Museum', 'Museo', 'Entrada general gratuita, reserva recomendada y actividad familiar.', 'Science Museum, London', 51.4978, -0.1745, { reservationRequired: true }),
  activity(3, '2026-08-03', '15:00', 'Hyde Park', 'Parque', 'Paseo y descanso.', 'Hyde Park, London', 51.5073, -0.1657),
  activity(4, '2026-08-03', '16:00', 'Diana Memorial Fountain', 'Actividad infantil', 'Actividad familiar si el tiempo acompaña.', 'Diana Memorial Fountain, London', 51.5048, -0.1717),
  activity(5, '2026-08-03', '18:00', 'Oxford Street', 'Tienda', 'Compras de marcas económicas. Sugerencias: Primark, TK Maxx, Uniqlo, H&M, Zara. Hamleys como alternativa familiar.', 'Oxford Street, London', 51.5154, -0.141),
  activity(1, '2026-08-04', '09:30', 'Tower of London', 'Monumento', 'Actividad opcional de pago. Reserva recomendada. Marcada como premium.', 'Tower of London', 51.5081, -0.0759, { priority: 'Premium', reservationRequired: true, estimatedTotalPrice: 120 }),
  activity(2, '2026-08-04', '12:00', 'Tower Bridge', 'Monumento', 'Paseo y fotografías. Entrada interior opcional.', 'Tower Bridge, London', 51.5055, -0.0754),
  activity(3, '2026-08-04', '13:30', 'Borough Market', 'Mercado', 'Comida y visita.', 'Borough Market, London', 51.5054, -0.0911),
  activity(4, '2026-08-04', '15:30', 'Southwark', 'Paseo', 'Paseo por la zona.', 'Southwark, London', 51.505, -0.09),
  activity(5, '2026-08-04', '16:30', 'Barco por el Támesis', 'Transporte', 'Trayecto con Thames Clippers. Destino sugerido: Greenwich.', 'London Bridge City Pier to Greenwich Pier', 51.5077, -0.0877),
  activity(6, '2026-08-04', '18:00', 'Greenwich', 'Parque', 'Paseo por el parque y zona del meridiano. Entrada de pago opcional.', 'Greenwich Park, London', 51.4769, -0.0005),
  activity(1, '2026-08-05', '09:00', 'Segundo alojamiento', 'Alojamiento', '100 Warwick Way, Westminster Borough, Londres SW1V 1SD.', '100 Warwick Way, London SW1V 1SD', 51.4915, -0.1443),
  activity(2, '2026-08-05', '10:30', 'Victoria y Belgravia', 'Paseo', 'Paseo ligero adaptable según cansancio y equipaje.', 'Victoria, London', 51.4965, -0.1439),
  activity(3, '2026-08-05', '12:30', 'Comida temprana', 'Restaurante', 'Cerca de Victoria. Sugerencia: Market Halls Victoria.', 'Market Halls Victoria, London', 51.4963, -0.1437),
  activity(4, '2026-08-05', '14:45', 'Recogida de equipaje', 'Reserva', 'Aviso prioritario.', 'Victoria, London', 51.4965, -0.1439, { priority: 'Alta', notes: 'Confirmar punto y horario de recogida.' }),
  activity(5, '2026-08-05', '15:45', 'Traslado a Londres Luton', 'Transporte', 'Taxi hasta St Pancras, Luton Airport Express y Luton DART. Objetivo: terminal sobre las 17:00.', 'London St Pancras to London Luton Airport', 51.53, -0.1255, { priority: 'Alta' }),
  activity(6, '2026-08-05', '20:00', 'Vuelo Londres Luton-Alicante', 'Transporte', 'Vuelo easyJet U22315. Llegada a Alicante a las 23:40.', 'London Luton Airport to Alicante Airport', 51.8747, -0.3683, { status: 'Confirmado', tags: ['U22315', 'aeropuerto'] }),
];

export const initialAccommodations: Accommodation[] = [
  {
    id: 'accommodation-theobalds',
    tripId: londonTripId,
    name: 'Flat 3, 23 Theobalds Road',
    address: 'Flat 3, 23 Theobalds Road, Camden, Londres WC1X 8SL',
    phone: '',
    checkIn: '',
    checkOut: '',
    startDate: '2026-08-01',
    endDate: '2026-08-05',
    entryInstructions: '',
    luggageNotes: '',
    notes: 'Fechas completamente editables.',
    lat: 51.5194,
    lng: -0.1166,
    images: [],
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'accommodation-warwick-way',
    tripId: londonTripId,
    name: '100 Warwick Way',
    address: '100 Warwick Way, Westminster Borough, Londres SW1V 1SD',
    phone: '',
    checkIn: '',
    checkOut: '',
    startDate: '2026-08-05',
    endDate: '2026-08-05',
    entryInstructions: '',
    luggageNotes: '',
    notes: 'Segundo alojamiento. Fechas editables.',
    lat: 51.4915,
    lng: -0.1443,
    images: [],
    active: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const initialTransports: Transport[] = [
  { id: 'transport-vy8475', tripId: londonTripId, type: 'Vuelo', origin: 'Alicante', destination: 'Londres Gatwick', date: '2026-08-01', time: '06:05', company: 'Vueling', serviceNumber: 'VY8475', terminal: 'Gatwick terminal sur', bookingCode: '', luggage: 'Revisar medidas de equipaje de mano en la aerolínea antes de salir.', notes: '', status: 'Confirmado', reminder: 'Llegar con margen al aeropuerto.' },
  { id: 'transport-u22315', tripId: londonTripId, type: 'Vuelo', origin: 'Londres Luton', destination: 'Alicante', date: '2026-08-05', time: '20:00', company: 'easyJet', serviceNumber: 'U22315', terminal: 'Luton', bookingCode: '', luggage: 'Revisar medidas de equipaje de mano en la aerolínea antes del viaje.', notes: '', status: 'Confirmado', reminder: 'Salir de Londres entre 15:45 y 16:00.' },
];

export const initialPackingItems: PackingItem[] = [
  'Pasaportes o DNI vigentes',
  'Tarjetas sanitarias y seguro',
  'Cargadores y adaptadores UK',
  'Medicamentos habituales',
  'Ropa cómoda para lluvia',
  'Snacks para niños',
  'Copias de reservas',
].map((title, index) => ({
  id: `packing-${index + 1}`,
  tripId: londonTripId,
  list: index < 2 ? 'Documentación' : index === 3 ? 'Medicamentos' : 'Equipaje',
  title,
  done: false,
  person: '',
  quantity: 1,
  notes: '',
  order: index + 1,
}));

export const initialReminders: Reminder[] = [
  { id: 'reminder-guard', tripId: londonTripId, title: 'Comprobar cambio de guardia', date: '2026-08-02', time: '08:30', notes: 'Revisar calendario oficial.', done: false },
  { id: 'reminder-luggage', tripId: londonTripId, title: 'Recoger equipaje', date: '2026-08-05', time: '14:45', notes: 'Aviso prioritario.', done: false },
];

export const initialSettings: AppSettings = {
  id: 'settings',
  initialized: true,
  activeTripId: londonTripId,
  budgetGbp: 900,
  gbpToEur: 1.18,
  theme: 'system',
  flightProvider: 'manual',
  flightAutoUpdate: false,
  flightNotifications: false,
  flightDataSaver: true,
  flightWifiOnly: false,
};

const flightBase = {
  tripId: londonTripId,
  estimatedDepartureTime: '',
  actualDepartureTime: '',
  estimatedArrivalTime: '',
  actualArrivalTime: '',
  departureTerminal: '',
  gate: '',
  checkInCounter: '',
  baggageBelt: '',
  delayMinutes: 0,
  aircraftType: '',
  aircraftRegistration: '',
  bookingReference: '',
  ticketNumber: '',
  includedBaggage: 'Consultar la reserva y las condiciones oficiales de la aerolínea.',
  notes: '',
  lastStatusProvider: 'Manual' as const,
  lastUpdatedAt: '',
  lastCheckedAt: '',
  lastUpdateError: '',
  autoUpdateEnabled: false,
  alertsEnabled: true,
  manualFields: {},
  automaticConflicts: {},
  createdAt: now,
  updatedAt: now,
};

export const initialFlights: Flight[] = [
  {
    ...flightBase,
    id: 'flight-vy8475-2026-08-01',
    airline: 'Vueling',
    airlineIata: 'VY',
    flightNumber: 'VY8475',
    normalizedFlightNumber: 'VY8475',
    lookupVariants: ['VY8475', 'VY 8475'],
    scheduledDate: '2026-08-01',
    departureAirport: 'Alicante-Elche Miguel Hernández',
    departureIata: 'ALC',
    arrivalAirport: 'Londres Gatwick',
    arrivalIata: 'LGW',
    scheduledDepartureTime: '06:05',
    scheduledArrivalTime: '07:50',
    arrivalTerminal: 'Sur',
    status: 'Programado',
    officialTrackingUrl: 'https://www.vueling.com/es/vueling-servicios/prepara-tu-viaje/informacion-de-vuelos/estado-de-vuelos',
    departureAirportUrl: 'https://www.aena.es/es/alicante-elche-miguel-hernandez/vuelos.html',
    arrivalAirportUrl: 'https://www.gatwickairport.com/flights/',
  },
  {
    ...flightBase,
    id: 'flight-u22315-2026-08-05',
    airline: 'easyJet',
    airlineIata: 'U2',
    flightNumber: 'U22315',
    normalizedFlightNumber: 'U22315',
    lookupVariants: ['U22315', 'U2 2315', 'EZY2315'],
    scheduledDate: '2026-08-05',
    departureAirport: 'Londres Luton',
    departureIata: 'LTN',
    arrivalAirport: 'Alicante-Elche Miguel Hernández',
    arrivalIata: 'ALC',
    scheduledDepartureTime: '20:00',
    scheduledArrivalTime: '23:40',
    arrivalTerminal: '',
    status: 'Programado',
    officialTrackingUrl: 'https://www.easyjet.com/es/flight-tracker',
    departureAirportUrl: 'https://www.london-luton.co.uk/flights',
    arrivalAirportUrl: 'https://www.aena.es/es/alicante-elche-miguel-hernandez/vuelos.html',
  },
];
